### ISSUE TITLE
index out of bounds in Integrator.h

### ISSUE THREAD

**Issue by gfinak** [yixuan/RcppNumerical#1]
In Integrator.h, line 268

```
for (int k = 0; k < m_numSubintervals; ++k)
        {
            integral += m_integralList[k];
}
```

`m_numSubintervals` can exceed  `m_maxSubintervals` in some cases, since the main loop limit is `<=m_maxSubintervals`. Therefore `k` can equal `m_maxSubintervals`, causing the indexing `m_integralList[k]` to fail an assertion that `k < m_integralList.size()`.

I've encountered this in some of my own code and tracked it down with lldb, (no short reproducible example at the moment, this seems to be an extreme edge case). 
My quick fix was to test `m_numSubintervals > m_maxSubintervals` and set them equal if true. 
I'm sure there's a cleaner fix.

**Comment by yixuan** [comment]
Hi @gfinak , thanks for the careful examination! I'll also take a look later.
Maybe you could also raise an issue at https://github.com/tbs1980/NumericalIntegration ? For `RcppNumerical` is essentially porting that library into the package.

**Comment by gfinak** [comment]
Some more details about the issue are at tbs1980/NumericalIntegration#8

**Comment by gfinak** [comment]
Based on discussions at the other repo, the following resolves the issue:
starting at line 213,  moving the test for the maximum number of iterations outside the check on `errorSum>errorBound`, ensures the error flag is set when the maximum number of iterations is reached, regardless of the accuracy of the integration. This ensures the main loop breaks at the end, and the counter is not incremented beyond the maximum index. 

```
// Set error flag in the case that the number of subintervals has reached the max allowable.
if (m_numSubintervals == m_maxSubintervals)
{
         m_errorCode = 1;
}
if (errorSum > errorBound)
            {
                // Test for roundoff error and set error flag.
                else if (roundOff1 >= 6 || roundOff2 >= 20)
                {
                    m_errorCode = 2;
                }
                // Set m_error_code in the case of poor integrand behaviour within
                // the integration range.
                else if ((std::max)(abs(lower1), abs(upper2))
                    <= (Eigen::NumTraits<Scalar>::epsilon() * Scalar(100.) + Scalar(1.))
                    * (abs(lower2) + (std::numeric_limits<Scalar>::min)() * Scalar(1.e3) ))
                {
                    m_errorCode = 3;
                }
            }
```

**Comment by yixuan** [comment]
Great! I see that there is an alternative solution provided by Mark, so which one do you prefer? Or I can wait for their final decision and synchronize `RcppNumerical` with it.

Again, thanks for your time on this.

**Comment by gfinak** [comment]
Mark's is preferred, keeps all the tests in one place.

**Comment by yixuan** [comment]
Would you like to submit a PR so that I could merge your commit?
