### ISSUE TITLE
Integration over an infinite interval

### ISSUE THREAD

**Issue by rstub** [yixuan/RcppNumerical#10]
I have recently written a template class and wrpper function for `Numer::integrate` that allows for integration over an infinite interval, c.f. https://stubner.me/2019/07/numerical-integration-in-rcpp-part-2/. Woudl you be interested in integrating this into RcppNumerical?

**Comment by yixuan** [comment]
This looks great! Are you interested in submitting a PR? I'd like to add you to the author list. Thank you!

**Comment by rstub** [comment]
Sure. Feel free to add me as contributor or author as you see fit.

**Comment by rstub** [comment]
BTW, @eddelbuettel asked me if I would like to make a Rcpp-gallery post out of my blog post. Since there hasn't been one on RcppNumerical in the first place: How about we write one together? Partly introducing the package and partly describing these transformations for infinite intervals?

**Comment by yixuan** [comment]
That would be great. I think we can start with my [old post on RcppNumerical](https://statr.me/2016/04/rcppnumerical-numerical-integration-optimization-rcpp/), and you can add the new feature on infinite interval.

**Comment by rstub** [comment]
@yixuan I have created a first draft at https://github.com/rstub/rcpp-gallery/blob/rcppnumerical/src/2019-08-07-rcppnumerical-intro.Rmd with a sort of preview at https://github.com/rstub/rcpp-gallery/blob/rcppnumerical/_posts/2019-08-07-rcppnumerical-intro.md. I had the impression that it was getting sort of long and therefore shortened the parts on multi-dimensional integration and optimization. Let me know what you think.

**Comment by rstub** [comment]
@yixuan Have you had time to look at my draft?

**Comment by yixuan** [comment]
Oops, I carelessly missed this thread when I was doing something else at that moment. Please allow me a few days to submit the new version to CRAN, so that the code in the article can run smoothly. I do apologize for the long delay.

**Comment by yixuan** [comment]
@rstub I have changed the code a little bit to make it compatible with the old API (https://github.com/yixuan/RcppNumerical/commit/39c2df30771add05425f8434d1abbf94aef690fb). The outcome doesn't differ much. If you also agree on this I will go and submit it to CRAN.

**Comment by rstub** [comment]
LGTM!
