### ISSUE TITLE
make lbfgs parameters accessible

### ISSUE THREAD

**Issue by BenoitLondon** [yixuan/RcppNumerical#5]
HI,
great work!
I have a request though :)

as far as I understand, the parameters like m for lbfgs are set by default to 6 in the wrapper function optim_lbfgs

Would it be possible to add them in this function arguments or make another function that takes a LBFGS_Params as argument? I understand m=6 is working most of the time but there are situations I found where increasing m was speeding up convergence.
Or maybe you assume we write our own wrapper function? 
Thanks

**Comment by yixuan** [comment]
Hi, thanks for the suggestion. I would say that my original thought is that people can use the library in both quick-and-dirty and advanced ways. The `optim_lbfgs` function just provides a very simplified and minimal interface to access an LBFGS solver, which should be sufficient for most cases.
You can absolutely tune other parameters by using the "raw" [LBFGS++](https://github.com/yixuan/LBFGSpp) interface that allows you to pass in an `LBFGSParam` object to set many other options (see the [API](http://yixuan.cos.name/LBFGSpp/doc/classLBFGSpp_1_1LBFGSParam.html)). `RcppNumerical` simply includes `LBFGS++` in the header file.

**Comment by BenoitLondon** [comment]
Ok thanks
