### ISSUE TITLE
failure of a double integral

### ISSUE THREAD

**Issue by stla** [yixuan/RcppNumerical#6]
Hello, 

 Here is the code:

```
// [[Rcpp::depends(RcppEigen)]]
// [[Rcpp::depends(RcppNumerical)]]
#include <RcppNumerical.h>
#include <cmath>
using namespace Numer;

class MyIntegrand: public MFunc
{
private:
  double a;
public:
  MyIntegrand(double& a_) : a(a_) {}
  double operator()(Constvec& x)
  {
    double u = 1.0 - fmax(x[0], x[1]);
    double v = fmin(x[0], x[1]);
    return pow(1.0-u-v, a);
  }
};

// [[Rcpp::export]]
Rcpp::List myIntegral(double a)
{
  MyIntegrand f(a);  
  Eigen::VectorXd lower(2);
  lower << 0, 0;
  Eigen::VectorXd upper(2);
  upper << 1, 1;
  double err_est;
  int err_code;
  double res = integrate(f, lower, upper, err_est, err_code, 
                         10000000, 1e-14, 1e-14);
  return Rcpp::List::create(
    Rcpp::Named("approximate") = res,
    Rcpp::Named("error_estimate") = err_est,
    Rcpp::Named("error_code") = err_code
  );
}
```

The integral is correctly evaluated when the parameter `a` is integer, but it always return `NaN` when it is not integer:
```
> myIntegral(2)
$approximate
[1] 0.1666667

$error_estimate
[1] 4.315166e-15

$error_code
[1] 0

> myIntegral(2.1)
$approximate
[1] NaN

$error_estimate
[1] NaN

$error_code
[1] 0
```

I believe the reason is the following one. The value of `1.0-u-v` in the integrand is sometimes negative, therefore `pow(1.0-u-v, a)` is `NaN`. 

But it is theoretically impossible that `1.0-u-v`  is negative: 
```
    double u = 1.0 - fmax(x[0], x[1]);
    double v = fmin(x[0], x[1]);
    return pow(1.0-u-v, a);
```
The function is integrated over the square `[0,1] x [0,1]`, and you can easily check that `1.0-u-v` should always lie between `0` and `1`. So it looks like the domain of integration goes beyond the square.

**Comment by stla** [comment]
> it looks like the domain of integration goes beyond the square

No, that's not the reason. I've tried to integrate the following function and there's no problem:

```
    if(x[0]>1 || x[0]<0 || x[1]>1 || x[1]<0){
      return 0/0;
    }
    return 1.0;
```

I don't understand what's going on.

**Comment by stla** [comment]
Well, that does not explain the issue, but as a workaround I can replace `1.0-u-v` with `fabs(x[0]-x[1])`.

If one integrates the following function:
```
    double u = 1.0 - fmax(x[0], x[1]);
    double v = fmin(x[0], x[1]);
    if(fabs(x[0]-x[1]) != (1.0-u-v)){
      return(1);
    }
    return(0);
```
Then the result is not 0. However, it should be 0.

**Comment by stla** [comment]
I close because this is apparently a numerical issue with `fmin` and `fmax`.

**Comment by yixuan** [comment]
I lost the context of this conversation, but indeed there are some rounding errors here. If you print the value of `1.0 - u - v` in each function evaluation you will find that there is one `-5.55112e-17` that causes the `NaN`.

Since you set the expected precision very high (1e-14), you really need to be careful of the rounding errors, for example `fabs(x[0] - x[1])` is more accurate than `1.0 - u - v`.

**Comment by stla** [comment]
Thank you, I see. 
My goal was to evaluate the first [Appell function](http://mathworld.wolfram.com/AppellHypergeometricFunction.html). I know there is a one-dimensional integral representation but I did that "for fun", to give a try to RcppNumerical. Since the domain of integration is a triangle, I resort to this "trick" to integrate on a square.
