### ISSUE TITLE
Is LBFGS++ a thread safe implementation?

### ISSUE THREAD

**Issue by mattfidler** [yixuan/RcppNumerical#8]
Hi;  I was wondering if LBFGS is thread safe?

**Comment by mattfidler** [comment]
Also is there a way to save/reload the Hessian matrix in this routine.  I didn't see anything, and I wondered.

**Comment by yixuan** [comment]
If you are using [LBFGS++](https://github.com/yixuan/LBFGSpp) together with Eigen, then mostly yes. You just need to make sure no R/Rcpp objects are involved.

As far as I know the LBFGS algorithm does not explicitly form a Hessian matrix. It uses gradients to construct a low-rank approximation to the true Hessian.

**Comment by mattfidler** [comment]
In other BFGS algorithms, the first guess to the low-rank Hessian matrix is the identity or some scaled identity matrix.  If you have an idea of the low-rank approximation to the Hessian matrix you can prespecify the matrix and speed up the calculation, I think...

I use this for one of my packages to speed minimization of nonlinear mixed effects models using another BFGS minimizer.  I was wondering if it was possible here.  I couldn't see it in the documentation, though.

**Comment by mattfidler** [comment]
Thanks for your answers.
